# Molecule managed

FROM {{ item.image }}@{{ (lookup('pipe', 'cat ../container-hashes.yml')|from_yaml)[item.image_hash_lookup] }}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get upgrade -y && apt-get install -y python3 python3-requests sudo bash ca-certificates libssl-dev libelf-dev && apt-get clean; \
    fi

RUN apt-get install -y sudo paxctl
RUN adduser --disabled-password vagrant
RUN usermod -aG sudo vagrant

RUN paxctl -cm /usr/bin/python3

USER vagrant
