---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: grsecurity-build-stable3-buster
    image: debian
    image_hash_lookup: debian-buster
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    e: "@../ansible-override-vars.yml"
scenario:
  name: workstation
  test_sequence:
    # Far too many linting violations, punting on cleanup.
    # - lint
    - destroy
    - dependency
    - syntax
    - create
    - converge
    # No tests written yet, punting for now.
    # - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
