---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
platforms:
  - name: grsecurity-install-ubuntu-xenial
    box: bento/ubuntu-16.04
    instance_raw_config_args:
      - "vm.synced_folder './', '/vagrant', disabled: true"
  - name: grsecurity-install-debian-stretch
    box: debian/stretch64
    instance_raw_config_args:
      - "vm.synced_folder './', '/vagrant', disabled: true"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: install
verifier:
  name: testinfra
  lint:
    name: flake8
