---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: grsecurity-build-debian-stretch
    image: debian
    # Declare key for hash lookup in YAML config
    image_hash_lookup: debian-stretch

  - name: grsecurity-build-ubuntu-xenial
    image: ubuntu
    image_hash_lookup: ubuntu-xenial

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: container
verifier:
  name: testinfra
  lint:
    name: flake8
