---
- name: Create directory for downloaded files.
  file:
    state: directory
    dest: "{{ grsecurity_build_download_directory }}/"
    mode: "0755"

- name: Fetch SHA256 checksums for Linux source files.
  get_url:
    url: "{{ linux_checksums_url }}"
    dest: "{{ grsecurity_build_download_directory }}/"
  register: linux_source_checksums

  # The "sha256sums.asc" file is a signed file, so the one-argument format
  # to gpg is correct. Compare with the `gpg --verify` tasks in the
  # verify.yml task list, some of which must use the two-arg format.
- name: Verify GPG signature on SHA256 checksum file.
  command: gpg --verify {{ linux_source_checksums.dest }}
  changed_when: false

- name: Read checksum for kernel tarball.
  shell: >
    set -o pipefail
    | grep {{ linux_tarball_xz_filename | quote }}
    {{ linux_source_checksums.dest | quote }} | cut -d' ' -f1
  changed_when: false
  register: linux_tarball_checksum

- name: Fetch Linux kernel tarball.
  get_url:
    url: "{{ linux_tarball_xz_url }}"
    dest: "{{ grsecurity_build_download_directory }}/{{ linux_tarball_xz_filename }}"
    sha256sum: "{{ linux_tarball_checksum.stdout }}"

- name: Fetch Linux kernel tarball signature file.
  get_url:
    url: "{{ linux_tarball_signature_url }}"
    dest: "{{ grsecurity_build_download_directory }}/"
