---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Check for grsecurity login credentials.
      assert:
        that:
          - grsecurity_build_download_username != ''
          - grsecurity_build_download_password != ''
        msg: "You'll need to provide subscription creds via env var `GRSECURITY_USERNAME` and `GRSECURITY_PASSWORD`"
  roles:
    - role: ansible-role-grsecurity-build
  vars:
    grsecurity_build_strategy: ci-tinyconfig
    grsecurity_build_compile_command: "make -j{{ grsecurity_build_compile_jobs }} bindeb-pkg"
    grsecurity_build_env_vars_addtl:
      LOCALVERSION: "-{{ ansible_date_time.epoch }}"
    grsecurity_build_patch_type: stable3
