---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: grsec_build_stretch
    image: debian
    image_hash_lookup: debian-stretch
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    e: "@../ansible-override-vars.yml"
scenario:
  name: ci-minipli
  test_sequence:
    - lint
    - destroy
    - create
    - converge
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
