---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: grsecurity-rebuild-securedrop-trusty
    image: ubuntu:xenial-20190122
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: securedrop-rebuild
  test_sequence:
    # Far too many linting violations, punting on cleanup.
    # - lint
    - destroy
    - dependency
    - syntax
    - create
    - converge
    # No tests written yet, punting for now.
    # - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
